### ISSUE TITLE
Unable to detect soil we've fertilized

### ISSUE THREAD

**Issue by khanshoaib3** [Croutonic-Creations/SDV-AccessibleTiles#32]
Gar - "It shows soil that hasn't been fertilized. But once you do fertilize it with basic stuff it disappears from the automapper, basically."

**Comment by GrumpyCrouton** [comment]
Hmm, it should still show if there isn't something planted on it.

**Comment by GrumpyCrouton** [comment]
Will probably pull this from an older version because it used to work
