### ISSUE TITLE
Ladders and Shafts

### ISSUE THREAD

**Issue by Bartholomue** [Croutonic-Creations/SDV-AccessibleTiles#36]
Distinguish ladders and shafts in the Skull cavern. Right now they're both announced as ladders, which makes tracking the appropriate exit strategy difficult.

**Comment by GrumpyCrouton** [comment]
Will probably pull this from an older version because it used to work

**Comment by GrumpyCrouton** [comment]
It seems to already announce as "Up Ladder" for any up ladder, and "Ladder" for any down ladder. I think this is fine
