### ISSUE TITLE
Interrupted Path, Footsteps Persist 

### ISSUE THREAD

**Issue by Bartholomue** [Croutonic-Creations/SDV-AccessibleTiles#38]
If you're pathing to an object and for one reason or another your path is obstructed, your character may sometimes continue to play footstep sounds even if you move to another area. Selecting a new target to path to clears the problem once you successfully arrive at the new destination.

**Comment by GrumpyCrouton** [comment]
Not sure how much I can do about this. There is a callback that gets called when pathing ends that is supposed to stop the sounds and all of that. I guess this callback does not get called when the path is interrupted. I will have to look into it further

**Comment by GrumpyCrouton** [comment]
Possibly fixed in 5c3bfb5
