### ISSUE TITLE
Shadows Block Grid Navigation 

### ISSUE THREAD

**Issue by Bartholomue** [Croutonic-Creations/SDV-AccessibleTiles#46]
Accessible Tiles' grid navigation refuses to let you walk into shadows cast by buildings or objects. This is why we can't approach the boat to repair it, and it's why we sometimes can't go somewhere, even though it appears empty with no feedback of an obstacle. I don't know how that's reflected in map data, but if you need that info, I can grab debug mode and try to send you relevant info.

**Comment by GrumpyCrouton** [comment]
Can you give me an example of a place a shadow would be and maybe a time to be there?

**Comment by Bartholomue** [comment]
If you go to 49, 21 in town (off to the left in front of the community center) and try to walk left, you won't be able to with grid nav, even though it's an empty space. That spot is covered by a shadow cast from the building. I don't think time matters, as I'm being stopped even as early as 6 AM.
Another example is right in front of the boat you need to repair to go to Ginger Island. On the BoatTunnel map, stand at 6, 10 and try to walk north to approach the boat to interact with it. You won't be able to with grid nav turned on. My sighted assistance tells me that there is a shadow cast from underneath the boat.

**Comment by Bartholomue** [comment]
Seems to be fixed in Beta.

**Comment by GrumpyCrouton** [comment]
2f9997f
