### ISSUE TITLE
Custom Trackable POI's

### ISSUE THREAD

**Issue by Bartholomue** [Croutonic-Creations/SDV-AccessibleTiles#52]
Add in a hotkey to add a custom tracked point of interest. I know we've discussed using /track, but I think console commands are very user unintuitive. I can't count the number of people (including myself) who find console commands sometimes confusing.
Proposal: The hotkey would add the tile the farmer is facing as a custom nameable POI, following the Auto Travel UI design. It should be the tile the farmer's facing rather than the tile he's standing on, as that follows the way interactions are handled in Stardew, and it lets you track impassible tiles like counters which you cannot occupy.
Face a tile / object, press a button. You're then presented with a list of the custom POI's you've made. You should be able to use the UI to delete and rename POI's, similar to Auto Travel.
(Optional) You could press enter on an entry in the list to start pathing to it, though this isn't really the intended method of interaction.
Create a new Custom POI category that players can select with control page down / control page up. They could then use the standard auto pathing and informational hot keys.

**Comment by Bartholomue** [comment]
Now assignable in json.

**Comment by GrumpyCrouton** [comment]
Config added in 5c3bfb5

Could you make a separate issue for the Custom POI stuff? I still want to make it so you can add new values from in-game.
