### ISSUE TITLE
Remove Hard-Coded Control Key

### ISSUE THREAD

**Issue by Bartholomue** [Croutonic-Creations/SDV-AccessibleTiles#55]
Rather than relying on hard coded control key combinations, please convert those key combinations into configurable hotkeys. Control + Home to navigate to a target, for example, is used very often, and is probably slightly strenuous for people with dexterity issues or other disabilities. If we could design a custom input interface based on our preferences and capabilities, it would make the game a lot more pleasant to play.

**Comment by GrumpyCrouton** [comment]
I have no problem adding those keybinds to the config if they aren't already there.

I have no plans to make a custom interface to change keybinds. Though, I have considered making the Generic Mod Config Menu mod accessible. If I do end up doing that, I could implement that mod into AccessibleTiles and we would have a way to do it in-game. 

I may implement Generic Mod Config Menu regardless that was with sighted help it could be changed in-game without messing with the config file.

**Comment by Bartholomue** [comment]
Sorry. When I wrote interface, I meant how we decide to assign the buttons, as the buttons would become an access interface. I didn't mean design an actual interface to assign keys. Just the ability to rebind keys would be amazing. I'm thinking home to announce the tracked target, end to auto path to it, etc. This is just my setup, but I bet people with manual dexterity issues would appreciate being able to make the Accessible Tiles key combinations a single key press.

**Comment by GrumpyCrouton** [comment]
Yeah, I have no problem adding those keys to the config if they are not already there as I said.

**Comment by GrumpyCrouton** [comment]
Config keys added in 5c3bfb5
