### ISSUE TITLE
Beta Missing Features

### ISSUE THREAD

**Issue by Bartholomue** [Croutonic-Creations/SDV-AccessibleTiles#58]
The change sorting order button is missing in the beta, which also means you can't force the mod to update its list of objects. I just harvested a bunch of spring onions and AT is still insisting there's a spring onion where there isn't, but I can't force it to update its list of objects any more. Control + Home used to say it couldn't find the item you're trying to move to, then update itself and put your highlight on the new item.
Could the update also be tied to the stop movement button as well as the sort order?

**Comment by GrumpyCrouton** [comment]
Added in 7acfeb6
