### ISSUE TITLE
Beta Verbosity Options

### ISSUE THREAD

**Issue by Bartholomue** [Croutonic-Creations/SDV-AccessibleTiles#59]
I find AT slightly too verbose for my own personal tastes. When I'm navigating between objects, I don't need to keep hearing what category the object is in. When I'm navigating categories, I don't need to hear the word object after the category name.
Could you introduce a verbosity option to trim down spoken text?
1. When selecting an object, only speak the object name. Example: stone.
2. When selecting a category, only have it say the name of the category, a comma for a slight pause, then the object that's highlighted in the category. Example: Debris, stone.
3. When pathing to an object, no speech is required because of the footsteps.

**Comment by GrumpyCrouton** [comment]
7be04a3
