### ISSUE TITLE
Grid movement does not work when using  a controller in the new 3.0.0 version

### ISSUE THREAD

**Issue by ohylli** [Croutonic-Creations/SDV-AccessibleTiles#66]
In the old version grid movement worked when I moved my character using the d-pad on an Xbox one controller. In the new 3.0.0 version moving with the controller ignores the grid movement. The character moves immediately when trying to move to a direction the character is not facing and one press of a d-pad direction does not necessarily move the character one tile.

**Comment by ohylli** [comment]
Thank you for the quick fix. However the movement does not yet work exactly the same way than in the older versions. Namely you cannot hold down a d-pad direction to continuously move to that direction. Instead you have to press a direction to move one tile release it and press again to move again one tile. I hope this could be changed so that it works like it used to.

**Comment by GrumpyCrouton** [comment]
Interesting, I thought I tested what you described. I'll take another look, sorry about that
