### ISSUE TITLE
Unresponsive Direction Changes

### ISSUE THREAD

**Issue by Bartholomue** [Croutonic-Creations/SDV-AccessibleTiles#69]
AT is a lot less responsive than it used to be. If I'm moving in a direction then instantly turn, it will not take the new direction, no matter how long I hold it. This means that if I run in to a wall, pressing another direction won't let me move away from it unless I deliberately paused an unnatural period.

**Comment by GrumpyCrouton** [comment]
This is related to the amount of time between steps. Maybe I can bypass this timer for turning
