### ISSUE TITLE
Proximity Sorting

### ISSUE THREAD

**Issue by Bartholomue** [Croutonic-Creations/SDV-AccessibleTiles#73]
Despite setting sort by proximity to enabled, I'm still seeing archeology house first, even though I'm standing right in front of the community center and the archeology house entrance is 84 tiles away. Is this intentional? This is also reflected in the characters category.

**Comment by Bartholomue** [comment]
I think you misunderstood my issue. The objects in the entrance category were not being properly organized. Regardless, this issue only seems to be exhibited because I was testing stardew expanded. It works fine in vanilla.

**Comment by GrumpyCrouton** [comment]
Oh my bad. Yeah I am not planning on supporting Stardew Expanded currently. Maybe in the future
