### ISSUE TITLE
Add Object Count Token

### ISSUE THREAD

**Issue by Bartholomue** [Croutonic-Creations/SDV-AccessibleTiles#74]
As requested on Discord: Add a {count} token to announce how many of an object there are.

**Comment by GrumpyCrouton** [comment]
I don't think this is possible currently. 

We would have to update Stardew Access to return the amount of any object there is. I may be able to add this for some objects, but for a majority of things AT has no idea how many there are. It only sees the closest one, as determined by Stardew Access 

Closing for now.
